const LANGUAGES = {
    en: { label: 'English', code: 'en-IN', dir: 'ltr' },
    hi: { label: 'हिन्दी', code: 'hi-IN', dir: 'ltr' },
    ta: { label: 'தமிழ்', code: 'ta-IN', dir: 'ltr' },
    te: { label: 'తెలుగు', code: 'te-IN', dir: 'ltr' },
    kn: { label: 'ಕನ್ನಡ', code: 'kn-IN', dir: 'ltr' },
    bn: { label: 'বাংলা', code: 'bn-IN', dir: 'ltr' },
    mr: { label: 'मराठी', code: 'mr-IN', dir: 'ltr' }
};

const UI = {
    en: {
        greeting: 'Hey Students! 👋',
        tagline: 'Learn smarter, not harder.',
        appName: 'VidyaBodh',
        selectLang: 'Choose your language to begin',
        continue: 'Continue',
        enterName: 'What is your name?',
        namePlaceholder: 'Enter your name…',
        selectClass: 'Select your class',
        startLearning: 'Start Learning',
        watchVideo: 'Watch & Learn',
        startQuiz: 'Start Quiz',
        voicePrompt: 'Tell me in your own words — why did you choose this answer?',
        voiceBtn: 'Tap to Speak',
        voiceListening: 'Listening…',
        voiceDone: 'Done',
        voiceSkip: 'Skip',
        next: 'Next Question',
        submit: 'Submit Quiz',
        result: 'Your Result',
        understood: 'True Understanding',
        confused: 'Concept Confusion',
        misconception: 'Misconception',
        rote: 'Rote Learning',
        resultMsgs: {
            understood: 'Excellent! You truly understand this concept.',
            confused: 'Almost there! One key link is missing.',
            misconception: 'Let\'s revisit this concept together.',
            rote: 'You know the answer, but let\'s build the reason too!'
        },
        subjects: { science: 'Science', math: 'Mathematics' },
        skip: 'Skipped',
        watched: 'Watched',
        classLabel: 'Class',
        homeGreeting: 'Welcome back',
        chooseTopic: 'Choose a Topic',
        layer1: 'Concept',
        layer2: 'Common Confusion',
        layer3: 'Story',
        nextLesson: 'Next Lesson'
    },
    hi: {
        greeting: 'नमस्ते छात्रों! 👋',
        tagline: 'स्मार्ट तरीके से सीखो।',
        appName: 'विद्याबोध',
        selectLang: 'अपनी भाषा चुनें',
        continue: 'आगे बढ़ें',
        enterName: 'आपका नाम क्या है?',
        namePlaceholder: 'अपना नाम लिखें…',
        selectClass: 'अपनी कक्षा चुनें',
        startLearning: 'सीखना शुरू करें',
        watchVideo: 'देखें और सीखें',
        startQuiz: 'प्रश्नोत्तरी शुरू करें',
        voicePrompt: 'अपने शब्दों में बताओ — तुमने यह उत्तर क्यों चुना?',
        voiceBtn: 'बोलने के लिए दबाएं',
        voiceListening: 'सुन रहे हैं…',
        voiceDone: 'हो गया',
        voiceSkip: 'छोड़ें',
        next: 'अगला प्रश्न',
        submit: 'जमा करें',
        result: 'आपका परिणाम',
        understood: 'सच्ची समझ',
        confused: 'अवधारणा भ्रम',
        misconception: 'गलत धारणा',
        rote: 'रटना',
        resultMsgs: {
            understood: 'बहुत बढ़िया! आपने इस विषय को सच में समझा।',
            confused: 'लगभग सही! एक कड़ी जोड़ना बाकी है।',
            misconception: 'आइए इस विषय को फिर से देखें।',
            rote: 'उत्तर तो पता है, पर कारण भी जानते हैं!'
        },
        subjects: { science: 'विज्ञान', math: 'गणित' },
        skip: 'छोड़ा',
        watched: 'देखा',
        classLabel: 'कक्षा',
        homeGreeting: 'वापस स्वागत है',
        chooseTopic: 'विषय चुनें',
        layer1: 'अवधारणा',
        layer2: 'सामान्य भ्रम',
        layer3: 'कहानी',
        nextLesson: 'अगला पाठ'
    },
    ta: {
        greeting: 'வணக்கம் மாணவர்களே! 👋',
        tagline: 'புத்திசாலித்தனமாக கற்றுக்கொள்.',
        appName: 'வித்யாபோத்',
        selectLang: 'உங்கள் மொழியை தேர்வு செய்யுங்கள்',
        continue: 'தொடரவும்',
        enterName: 'உங்கள் பெயர் என்ன?',
        namePlaceholder: 'பெயரை உள்ளிடுங்கள்…',
        selectClass: 'உங்கள் வகுப்பை தேர்வு செய்யுங்கள்',
        startLearning: 'கற்றலைத் தொடங்குங்கள்',
        watchVideo: 'பார்க்கவும் & கற்கவும்',
        startQuiz: 'வினாடி வினா தொடங்கு',
        voicePrompt: 'உங்கள் வார்த்தைகளில் சொல்லுங்கள் — இந்த பதிலை ஏன் தேர்ந்தெடுத்தீர்கள்?',
        voiceBtn: 'பேச தட்டவும்',
        voiceListening: 'கேட்கிறோம்…',
        voiceDone: 'முடிந்தது',
        voiceSkip: 'தவிர்க்கவும்',
        next: 'அடுத்த கேள்வி',
        submit: 'சமர்ப்பிக்கவும்',
        result: 'உங்கள் முடிவு',
        understood: 'உண்மையான புரிதல்',
        confused: 'கருத்து குழப்பம்',
        misconception: 'தவறான நம்பிக்கை',
        rote: 'மனப்பாடம்',
        resultMsgs: {
            understood: 'அருமை! நீங்கள் உண்மையிலேயே புரிந்துகொண்டீர்கள்.',
            confused: 'கிட்டத்தட்ட சரி! ஒரு இணைப்பு மட்டும் தேவை.',
            misconception: 'இந்த கருத்தை மீண்டும் பார்ப்போம்.',
            rote: 'பதில் தெரியும், ஆனால் காரணமும் அறிவோம்!'
        },
        subjects: { science: 'அறிவியல்', math: 'கணிதம்' },
        skip: 'தவிர்த்தது',
        watched: 'பார்த்தது',
        classLabel: 'வகுப்பு',
        homeGreeting: 'மீண்டும் வரவேற்கிறோம்',
        chooseTopic: 'தலைப்பை தேர்வு செய்',
        layer1: 'கருத்து',
        layer2: 'பொதுவான குழப்பம்',
        layer3: 'கதை',
        nextLesson: 'அடுத்த பாடம்'
    },
    te: {
        greeting: 'హలో విద్యార్థులు! 👋',
        tagline: 'తెలివిగా నేర్చుకో.',
        appName: 'విద్యాబోధ్',
        selectLang: 'మీ భాషను ఎంచుకోండి',
        continue: 'కొనసాగించు',
        enterName: 'మీ పేరు ఏమిటి?',
        namePlaceholder: 'మీ పేరు నమోదు చేయండి…',
        selectClass: 'మీ తరగతి ఎంచుకోండి',
        startLearning: 'నేర్చుకోవడం ప్రారంభించండి',
        watchVideo: 'చూడండి & నేర్చుకోండి',
        startQuiz: 'క్విజ్ ప్రారంభించు',
        voicePrompt: 'మీ మాటల్లో చెప్పండి — మీరు ఈ జవాబు ఎందుకు ఎంచుకున్నారు?',
        voiceBtn: 'మాట్లాడటానికి నొక్కండి',
        voiceListening: 'వింటున్నాము…',
        voiceDone: 'పూర్తయింది',
        voiceSkip: 'దాటవేయి',
        next: 'తదుపరి ప్రశ్న',
        submit: 'సమర్పించు',
        result: 'మీ ఫలితం',
        understood: 'నిజమైన అవగాహన',
        confused: 'భావన గందరగోళం',
        misconception: 'తప్పుడు నమ్మకం',
        rote: 'కంఠస్తం',
        resultMsgs: {
            understood: 'అద్భుతం! మీరు నిజంగా అర్థం చేసుకున్నారు.',
            confused: 'దాదాపు సరైంది! ఒక లింక్ తప్పింది.',
            misconception: 'ఈ భావనను మళ్లీ చూద్దాం.',
            rote: 'జవాబు తెలుసు, కారణం కూడా తెలుసుకుందాం!'
        },
        subjects: { science: 'విజ్ఞానం', math: 'గణితం' },
        skip: 'దాటవేశారు',
        watched: 'చూసారు',
        classLabel: 'తరగతి',
        homeGreeting: 'తిరిగి స్వాగతం',
        chooseTopic: 'అంశం ఎంచుకోండి',
        layer1: 'భావన',
        layer2: 'సాధారణ గందరగోళం',
        layer3: 'కథ',
        nextLesson: 'తదుపరి పాఠం'
    },
    kn: {
        greeting: 'ನಮಸ್ಕಾರ ವಿದ್ಯಾರ್ಥಿಗಳೇ! 👋',
        tagline: 'ಜಾಣ್ಮೆಯಿಂದ ಕಲಿಯಿರಿ.',
        appName: 'ವಿದ್ಯಾಬೋಧ್',
        selectLang: 'ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
        continue: 'ಮುಂದುವರಿಯಿರಿ',
        enterName: 'ನಿಮ್ಮ ಹೆಸರು ಏನು?',
        namePlaceholder: 'ನಿಮ್ಮ ಹೆಸರು ನಮೂದಿಸಿ…',
        selectClass: 'ನಿಮ್ಮ ತರಗತಿ ಆಯ್ಕೆ ಮಾಡಿ',
        startLearning: 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ',
        watchVideo: 'ನೋಡಿ & ಕಲಿಯಿರಿ',
        startQuiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಿ',
        voicePrompt: 'ನಿಮ್ಮ ಮಾತಿನಲ್ಲಿ ಹೇಳಿ — ಈ ಉತ್ತರ ಯಾಕೆ ಆರಿಸಿದಿರಿ?',
        voiceBtn: 'ಮಾತಾಡಲು ಒತ್ತಿ',
        voiceListening: 'ಕೇಳುತ್ತಿದ್ದೇವೆ…',
        voiceDone: 'ಮುಗಿದಿದೆ',
        voiceSkip: 'ಬಿಟ್ಟುಬಿಡಿ',
        next: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
        submit: 'ಸಲ್ಲಿಸಿ',
        result: 'ನಿಮ್ಮ ಫಲಿತಾಂಶ',
        understood: 'ನಿಜವಾದ ಅರಿವು',
        confused: 'ಪರಿಕಲ್ಪನೆ ಗೊಂದಲ',
        misconception: 'ತಪ್ಪು ನಂಬಿಕೆ',
        rote: 'ಕಂಠಪಾಠ',
        resultMsgs: {
            understood: 'ಅದ್ಭುತ! ನೀವು ನಿಜವಾಗಿಯೂ ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೀರಿ.',
            confused: 'ಬಹುತೇಕ ಸರಿ! ಒಂದು ಕೊಂಡಿ ಮಿಸ್ ಆಗಿದೆ.',
            misconception: 'ಈ ಪರಿಕಲ್ಪನೆಯನ್ನು ಮತ್ತೆ ನೋಡೋಣ.',
            rote: 'ಉತ್ತರ ಗೊತ್ತಿದೆ, ಕಾರಣವೂ ತಿಳಿಯೋಣ!'
        },
        subjects: { science: 'ವಿಜ್ಞಾನ', math: 'ಗಣಿತ' },
        skip: 'ಬಿಟ್ಟಿದ್ದಾರೆ',
        watched: 'ನೋಡಿದ್ದಾರೆ',
        classLabel: 'ತರಗತಿ',
        homeGreeting: 'ಮತ್ತೆ ಸ್ವಾಗತ',
        chooseTopic: 'ವಿಷಯ ಆಯ್ಕೆ ಮಾಡಿ',
        layer1: 'ಪರಿಕಲ್ಪನೆ',
        layer2: 'ಸಾಮಾನ್ಯ ಗೊಂದಲ',
        layer3: 'ಕಥೆ',
        nextLesson: 'ಮುಂದಿನ ಪಾಠ'
    },
    bn: {
        greeting: 'হ্যালো শিক্ষার্থীরা! 👋',
        tagline: 'স্মার্টভাবে শেখো।',
        appName: 'বিদ্যাবোধ',
        selectLang: 'আপনার ভাষা বেছে নিন',
        continue: 'এগিয়ে যান',
        enterName: 'তোমার নাম কী?',
        namePlaceholder: 'নাম লিখুন…',
        selectClass: 'তোমার শ্রেণি বেছে নাও',
        startLearning: 'শেখা শুরু করো',
        watchVideo: 'দেখো এবং শেখো',
        startQuiz: 'কুইজ শুরু করো',
        voicePrompt: 'তোমার নিজের কথায় বলো — এই উত্তরটি কেন বেছেছিলে?',
        voiceBtn: 'বলতে চাপুন',
        voiceListening: 'শুনছি…',
        voiceDone: 'শেষ',
        voiceSkip: 'এড়িয়ে যাও',
        next: 'পরের প্রশ্ন',
        submit: 'জমা দাও',
        result: 'তোমার ফলাফল',
        understood: 'সত্যিকারের বোঝাপড়া',
        confused: 'ধারণার বিভ্রান্তি',
        misconception: 'ভুল ধারণা',
        rote: 'মুখস্থ',
        resultMsgs: {
            understood: 'চমৎকার! তুমি সত্যিই বুঝেছ।',
            confused: 'প্রায় ঠিক! একটি যোগসূত্র বাকি।',
            misconception: 'এই ধারণাটি আবার দেখা যাক।',
            rote: 'উত্তর জানো, কারণটাও জানো!'
        },
        subjects: { science: 'বিজ্ঞান', math: 'গণিত' },
        skip: 'এড়িয়ে গেছে',
        watched: 'দেখেছে',
        classLabel: 'শ্রেণি',
        homeGreeting: 'আবার স্বাগতম',
        chooseTopic: 'বিষয় বেছে নাও',
        layer1: 'ধারণা',
        layer2: 'সাধারণ বিভ্রান্তি',
        layer3: 'গল্প',
        nextLesson: 'পরের পাঠ'
    },
    mr: {
        greeting: 'नमस्कार विद्यार्थींनो! 👋',
        tagline: 'हुशारीने शिका.',
        appName: 'विद्याबोध',
        selectLang: 'तुमची भाषा निवडा',
        continue: 'पुढे जा',
        enterName: 'तुमचे नाव काय आहे?',
        namePlaceholder: 'नाव टाका…',
        selectClass: 'तुमचा वर्ग निवडा',
        startLearning: 'शिकणे सुरू करा',
        watchVideo: 'पहा आणि शिका',
        startQuiz: 'प्रश्नमंजुषा सुरू करा',
        voicePrompt: 'तुमच्या शब्दांत सांगा — हे उत्तर का निवडले?',
        voiceBtn: 'बोलण्यासाठी दाबा',
        voiceListening: 'ऐकत आहोत…',
        voiceDone: 'झाले',
        voiceSkip: 'वगळा',
        next: 'पुढचा प्रश्न',
        submit: 'सबमिट करा',
        result: 'तुमचा निकाल',
        understood: 'खरी समज',
        confused: 'संकल्पना गोंधळ',
        misconception: 'चुकीची समजूत',
        rote: 'घोकंपट्टी',
        resultMsgs: {
            understood: 'शाब्बास! तुम्ही खरोखरच समजलात.',
            confused: 'जवळजवळ बरोबर! एक दुवा बाकी आहे.',
            misconception: 'ही संकल्पना पुन्हा पाहूया.',
            rote: 'उत्तर माहीत आहे, कारणही जाणून घेऊया!'
        },
        subjects: { science: 'विज्ञान', math: 'गणित' },
        skip: 'वगळले',
        watched: 'पाहिले',
        classLabel: 'वर्ग',
        homeGreeting: 'परत स्वागत',
        chooseTopic: 'विषय निवडा',
        layer1: 'संकल्पना',
        layer2: 'सामान्य गोंधळ',
        layer3: 'कथा',
        nextLesson: 'पुढचा धडा'
    }
};

function t(key) {
    const lang = Storage ? Storage.getLang() : 'en';
    return UI[lang]?.[key] || UI['en'][key] || key;
}